### ISSUE TITLE
[SCAN]: ses-xxx

### ISSUE THREAD

**Issue by bpinsard** [courtois-neuromod/floc#3]
### equipment

- [X] biopac
- [X] eyetracker
- [X] gamepad

### task-floc_run-01

- [X] series was completed.
- [X] sleep
- [ ] excessive motion
- [ ] eyetracking issues (crash, pupil loss)
- [ ] physio signal quality issue

### task-floc_run-02

- [X] series was completed.
- [ ] sleep
- [X] excessive motion
- [X] eyetracking issues (crash, pupil loss)
- [X] physio signal quality issue

**Comment by pbellec** [comment]
that's nice but the summary at the top is misleading: it looks like the aim would be to check all possible issues for any dataset.

**Comment by bpinsard** [comment]
Are you talking about the "equipment" section? It should be named "setup" or "equipment setup".
